### ISSUE TITLE
Fails on Android OnePlus 5

### ISSUE THREAD

**Issue by vHanda** [onepub-dev/dart_posix#4]
Hi.

I was trying this library out as an alternative to [os](https://github.com/dart-interop/os) (unmaintained). On my - `ONEPLUS A5000 (mobile) • 6bf122e6 • android-arm64  • Android 10 (API 29)`. I get the follow error -

```
Invalid argument(s): Failed to load dynamic library 'libc.so.6': dlopen failed: library "libc.so.6" not found
```

I tried changing `libc.so.6` to `libc.so` as the latter is what the `os` package uses, and that works for me (and about ~6k Android users). With that, the loading works but I then I get the following error -

```
Invalid argument(s): Failed to lookup symbol (undefined symbol: __errno_location)
```

I tried changing the relevant code to -

```dart
/// The error code set by various library functions.
int errno() => _errno.value;

/// Clear the errno by setting it to 0.
/// You should do this before calling a function that
/// may set errno.
void clearErrno() => _errno.value = 0;

final _errno = Libc().dylib.lookup<ffi.Int32>('errno');
```

But it also fails to find `errno`. Do you have any tips on how I can fix this?

**Comment by bsutton** [comment]
Have a look at this.

https://android.googlesource.com/kernel/lk/+/dima/for-travis/include/errno.h

**Comment by bsutton** [comment]
closing due to no response.

If someone wants to supply a PR to fix this it would be accepted.
