### ISSUE TITLE
Upgrade Dart version & ffigen?

### ISSUE THREAD

**Issue by jpnurmi** [onepub-dev/dart_posix#8]
With the latest Dart stable, array workarounds are no longer needed and the memory arena makes memory allocation less error-prone e.g. automatic free on early return.

**Comment by bsutton** [comment]
If you are happy to make the changes and the unit tests pass on happy to accept the change.

**Comment by bsutton** [comment]
i'm going to close this.

At this point I'm of the opinion - if it ain't broke don't fix it.

Going forward we probably should look to using this technique for any new functionality.
